name: Build Outline SDK AAR

on:
  workflow_dispatch:  # 手动触发
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04  # 使用稳定的Ubuntu版本
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Go 1.22.4
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'  # 使用兼容版本
        
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 21
        build-tools: 30.0.3
        ndk-version: 23.1.7779620
        
    - name: Install gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@v0.0.0-20231127183840-76ac6878050a
        go install golang.org/x/mobile/cmd/gobind@v0.0.0-20231127183840-76ac6878050a
        
    - name: Initialize gomobile
      run: |
        export ANDROID_HOME=$ANDROID_SDK_ROOT
        export ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/23.1.7779620
        gomobile init
        
    - name: Build mobileproxy AAR
      run: |
        export ANDROID_HOME=$ANDROID_SDK_ROOT
        export ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/23.1.7779620
        go get golang.org/x/mobile/bind
        go mod tidy
        gomobile bind -target=android -androidapi=21 -o mobileproxy.aar github.com/Jigsaw-Code/outline-sdk/x/mobileproxy
        
    - name: Upload AAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: outline-mobileproxy-aar
        path: mobileproxy.aar
